### ISSUE TITLE
Use different return code when some image lists aren't successfully processed

### ISSUE THREAD

**Issue by Misenko** [the-cloudkeeper-project/cloudkeeper#56]
When image list cannot be processed (unavailable server etc.) cloudkeeper logs this issue and continues with rest of the image lists. In other words this is not considered an error and return code for this case is 0. Cloudkeeper should return different return code to signalize the issue.

**Comment by Pansanel** [comment]
I catch the same issue with an unavailable server:
2018-04-04T14:22:01+02:00 [ERROR] 36957 : Unexpected error: Connection timed out - connect(2) for "155.210.198.193" port 80
/opt/cloudkeeper/embedded/lib/ruby/2.2.0/net/http.rb:879:in `initialize': Connection timed out - connect(2) for "155.210.198.193" port 80 (Errno::ETIMEDOUT)
	from /opt/cloudkeeper/embedded/lib/ruby/2.2.0/net/http.rb:879:in `open'
	from /opt/cloudkeeper/embedded/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
	from /opt/cloudkeeper/embedded/lib/ruby/2.2.0/timeout.rb:73:in `timeout'

In this case, the following image lists are not processed.
FYI, I have sent an email to the image owner to tell that the link is not working, but I have still no answer. We must ignore such errors.

**Comment by Misenko** [comment]
This seems like a different problem than the one I described in this issue. Can you give me a VO name so I can see it for myself?

**Comment by Pansanel** [comment]
It is vo.nbis.se

**Comment by Misenko** [comment]
I found out that what you described is a different problem and I opened an [issue](https://github.com/the-cloudkeeper-project/cloudkeeper/issues/57) for it.
