### ISSUE TITLE
Cloudkeeper CentOS7 packaging issue

### ISSUE THREAD

**Issue by Pansanel** [the-cloudkeeper-project/cloudkeeper#76]
Dears,

The Cloudkeeper RPM package available on:
http://repository.egi.eu/community/software/cloudkeeper/1.x/releases/sl/7/x86_64/RPMS/

have the following directories missing:
* ```/var/run/cloudkeeper```
* ```/var/lock/cloudkeeper```
* ```/var/log/cloudkeeper```

These directories should also owned by the cloudkeeper user.

**Comment by Misenko** [comment]
Hi Jerome,

I'm no longer going to support packaging for Cloudkeeper compoments as I mentioned in the recent email to FedCloud mailing list. Maybe @arax is willing to fix this, otherwise I'll close it as `wontfix`.

**Comment by arax** [comment]
I'm sorry. The "native" packaging for `cloudkeeper*` via `omnibus` is no longer supported.

**Comment by Misenko** [comment]
Alright then. Closing.
